version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: emojigen/node-py23:node12.6.0-py2.7.16-py3.7.3
    environment:
    steps:
      - checkout
      - run:
          name: System information
          command: |
            python3 --version
            pip3 --version
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Notify test started
          command: |
            pip3 install -q slackweb
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              python3 common/script/notify.py started
            fi
      - restore_cache:
          key: emoji-gen/web-main/{{ arch }}/{{ checksum "frontend/yarn.lock" }}/{{ checksum "server/requirements.txt" }}
      - run:
          name: Install dependencies (Python)
          command: |
            /usr/local/bin/pip3 install -q -r requirements.txt \
              --index-url https://repo.fury.io/emoji-gen/ --extra-index-url https://pypi.org/simple
          working_directory: server
      - run:
          name: Install dependencies (Node)
          command: yarn
          working_directory: frontend
      - run:
          name: Test (Node)
          command: |
            yarn test
            yarn run build
          working_directory: frontend
      - run:
          name: Check git dirty
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./common/script/is-git-dirty.sh
            fi
      - save_cache:
          key: emoji-gen/web-main/{{ arch }}/{{ checksum "frontend/yarn.lock" }}/{{ checksum "server/requirements.txt" }}
          paths:
            - ~/workspace/frontend/node_modules
            - ~/.cache/yarn/
            - ~/.cache/pip/
      - run:
          name: Notify test successful
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              python3 common/script/notify.py successful
            fi
      - deploy:
          name: Deploy to Production
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              curl -X POST "https://circleci.com/api/v1.1/project/github/pine/eg-fabric/tree/master?circle-token=$CIRCLE_TOKEN"
            fi
