version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: emojigen/docker-web-main
    steps:
      - checkout
      - run:
          name: Notify if in master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/notify/start-test.sh
            fi
      - restore_cache:
          key: Emoji-Web-{{ checksum "yarn.lock" }}-{{ checksum "requirements.txt" }}
      - run:
          name: System information
          command: |
            /usr/local/python/bin/python --version
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies (Python)
          command: |
            /usr/local/python/bin/pip install \
              -r requirements.txt \
              --index-url https://repo.fury.io/emoji-gen/ \
              --extra-index-url https://pypi.org/simple
      - run:
          name: Install dependencies (Node)
          command: yarn
      - run:
          name: Test (Node)
          command: |
            yarn test
            yarn run build
            if [ $CIRCLE_BRANCH = 'master' ]; then scripts/test/git-status.sh; fi
      - save_cache:
          key: Emoji-Web-{{ checksum "yarn.lock" }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
            - ~/.cache/pip/
      - run:
          name: Notify if in master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/notify/end-test.sh
            fi
      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy.sh
            fi
