version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: emojigen/emoji-circleci-dockerfile

    steps:
      - checkout
      - restore_cache:
          key: Emoji-Web-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            python3 --version
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Create virtualenv
          command: |
            if [ ! -d venv ]; then
              python3 -m venv venv
            fi
      - run:
          name: Activate virtualenv
          command: |
            . venv/bin/activate
      - run:
          name: Install dependencies (Python)
          command: pip3 install -r requirements.txt
      - run:
          name: Install dependencies (Node)
          command: yarn
      - run:
          name: Test (Node)
          command: |
            yarn test
            yarn run build
            if [ $CIRCLE_BRANCH = 'master' ]; then scripts/test/git-status.sh; fi
      - save_cache:
          key: Emoji-Web-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/workspace/venv
            - ~/.cache/yarn/
      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy.sh
            fi
