
templates:
  site_name: '絵文字ジェネレーター'
  site_lead: 'Slack 向け絵文字を無料で簡単生成'
  site_description: '絵文字ジェネレーターで、綺麗な絵文字を生成しよう! 好みのテキストと色を指定するだけで、便利なリアクション絵文字・スタンプが無料で簡単生成できます! Slack などチャットツールでの利用に最適! 絵文字でコミュニケーションを活発化しましょう。'

routes:
  default_font_key: 'notosans-mono-bold'
  default_text: '絵文\n字'
  default_color: '000000FF'
  default_background_color: 'FFFFFF00'

repos:
  fonts:
    'notosans-mono-bold':
      name: 'Noto Sans Mono CJK Bold'
      file: 'NotoSansMonoCJKjp-Bold.otf'
      type: 'ゴシック'
      order: 1
      enabled: 'on'
    'mplus-1p-black':
      name: 'M+ 1p black'
      file: 'mplus-1p-black.ttf'
      type: '極太ゴシック'
      order: 2
      enabled: 'on'
    'migu-1m-bold':
      name: 'Migu 1m bold'
      file: 'migu-1m-bold.ttf'
      type: 'ゴシック'
      order: 3
      enabled: 'off'
    'rounded-x-mplus-1p-black':
      name: 'Rounded M+ 1p black'
      file: 'rounded-x-mplus-1p-black.ttf'
      type: '丸ゴシック'
      order: 4
      enabled: 'on'
    'ipamjm':
      name: 'IPAmj明朝'
      file: 'ipamjm.ttf'
      type: '明朝'
      order: 5
      enabled: 'on'
    'LinLibertine_RBah':
      name: 'LinLibertine Bold'
      file: 'LinLibertine_RBah.ttf'
      type: '英字'
      order: 6
      enabled: 'on'
    'aoyagireisyoshimo':
      name: '青柳隷書しも'
      file: 'aoyagireisyosimo_otf_2_01.otf'
      type: '毛筆'
      order: 7
      enabled: 'on'
