ja:
  - typeface: 'ゴシック体'
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK Bold'
    path: 'cjk/NotoSansMonoCJKjp-Bold.otf'
  - typeface: '極太ゴシック体'
    key: 'mplus-1p-black'
    name: 'M+ 1p black'
    path: 'ja/mplus-1p-black.ttf'
  - type: '丸ゴシック体'
    key: 'rounded-x-mplus-1p-black'
    name: 'Rounded M+ 1p black'
    path: 'ja/rounded-x-mplus-1p-black.ttf'
  - type: '明朝体'
    key: 'ipamjm'
    name: 'IPAmj明朝'
    path: 'ja/ipamjm.ttf'
  - type: '毛筆'
    key: 'aoyagireisyoshimo'
    name: '青柳隷書しも'
    path: 'ja/aoyagireisyosimo_otf_2_01.otf'
  - type: '英字'
    key: 'LinLibertine_RBah'
    name: 'LinLibertine Bold'
    path: 'en/LinLibertine_RBah.ttf'
ko:
  - typeface: ''
    key: 'notosans-mono-bold'
    name: '본고딕 Bold'
    path: 'cjk/NotoSansMonoCJKjp-Bold.otf'
  - typeface: ''
    key: 'nanum-square-round-eb'
    name: '나눔스퀘어라운드 Extra Bold'
    path: 'ko/NanumSquareRoundOTFEB.otf'
  - typeface: ''
    key: 'nanum-myeongjo-extra-bold'
    name: '나눔명조 Extra Bold'
    path: 'ko/NanumMyeongjoExtraBold.ttf'
  - typeface: ''
    key: 'ebsjsk-bold'
    name: 'EBS 주시경체 Bold'
    path: 'ko/EBSJSK_Bold.otf'
  - typeface: ''
    key: 'hogook-bold'
    name: '호국체 Bold'
    path: 'ko/HogookBold_OTF.otf'
zh-Hans:
  - typeface: 'Sans-serif'
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK Bold'
    path: 'cjk/NotoSansMonoCJKjp-Bold.otf'
en:
  - typeface: 'Sans-serif'
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK Bold'
    path: 'cjk/NotoSansMonoCJKjp-Bold.otf'
  - typeface: '極太ゴシック体'
    key: 'mplus-1p-black'
    name: 'M+ 1p black'
    path: 'ja/mplus-1p-black.ttf'
  - type: '丸ゴシック体'
    key: 'rounded-x-mplus-1p-black'
    name: 'Rounded M+ 1p black'
    path: 'ja/rounded-x-mplus-1p-black.ttf'
  - type: '英字'
    key: 'LinLibertine_RBah'
    name: 'LinLibertine Bold'
    path: 'en/LinLibertine_RBah.ttf'
