ja:
  - typeface: 'ゴシック体'
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK JP Bold'
    path: 'ja/Noto_Sans_Mono_CJK_JP-Bold.otf'
  - typeface: '極太ゴシック体'
    key: 'mplus-1p-black'
    name: 'M+ 1p black'
    path: 'ja/mplus-1p-black.ttf'
  - type: '丸ゴシック体'
    key: 'rounded-x-mplus-1p-black'
    name: 'Rounded M+ 1p black'
    path: 'ja/rounded-x-mplus-1p-black.ttf'
  - type: '明朝体'
    key: 'ipamjm'
    name: 'IPAmj明朝'
    path: 'ja/ipamjm.ttf'
  - type: '毛筆'
    key: 'aoyagireisyoshimo'
    name: '青柳隷書しも'
    path: 'ja/aoyagireisyosimo_otf_2_01.otf'
  - type: '英字'
    key: 'LinLibertine_RBah'
    name: 'LinLibertine Bold'
    path: 'en/LinLibertine_RBah.ttf'
ko:
  - typeface: ''
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK KR Bold'
    path: 'ko/Noto_Sans_Mono_CJK_KR-Bold.otf'
  - typeface: ''
    key: 'nanum-square-round-eb'
    name: '나눔스퀘어라운드 Extra Bold'
    path: 'ko/NanumSquareRoundOTFEB.otf'
  - typeface: ''
    key: 'nanum-myeongjo-extra-bold'
    name: '나눔명조 Extra Bold'
    path: 'ko/NanumMyeongjoExtraBold.ttf'
  - typeface: ''
    key: 'ebsjsk-bold'
    name: 'EBS 주시경체 Bold'
    path: 'ko/EBSJSK_Bold.otf'
  - typeface: ''
    key: 'hogook-bold'
    name: '호국체 Bold'
    path: 'ko/HogookBold_OTF.otf'
zh-Hans:
  - typeface: ''
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK SC Bold'
    path: 'zh-Hans/Noto_Sans_Mono_CJK_SC-Bold.otf'
  # - typeface: ''
  #   key: 'hanyi_senty_tang'
  #   name: '思源宋体 Bold'
  #   path: 'zh-Hans/'
  - typeface: ''
    key: 'seto'
    name: '濑户字体'
    path: 'ja/SetoFont.ttf'
zh-Hant:
  - typeface: ''
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK TC Bold'
    path: 'zh-Hant/Noto_Sans_Mono_CJK_TC-Bold.otf'
  - typeface: ''
    key: 'gensenmarugothic_tw_ttf_bold'
    name: '源泉圓體 Bold'
    path: 'zh-Hant/GenSenMaruGothic_TW_TTF-Bold.ttf'
  - typeface: ''
    key: 'source_han_serif_tc'
    name: '思源宋體 Bold'
    path: 'zh-Hant/Source_Han_Serif_TC-Bold.otf'
  - typeface: ''
    key: 'seto'
    name: '瀨戶字體'
    path: 'ja/SetoFont.ttf'
en:
  - typeface: 'Sans-serif'
    key: 'notosans-mono-bold'
    name: 'Noto Sans Mono CJK Bold'
    path: 'ja/Noto_Sans_Mono_CJK_JP-Bold.otf'
  - typeface: '極太ゴシック体'
    key: 'mplus-1p-black'
    name: 'M+ 1p black'
    path: 'ja/mplus-1p-black.ttf'
  - type: '丸ゴシック体'
    key: 'rounded-x-mplus-1p-black'
    name: 'Rounded M+ 1p black'
    path: 'ja/rounded-x-mplus-1p-black.ttf'
  - type: '英字'
    key: 'LinLibertine_RBah'
    name: 'LinLibertine Bold'
    path: 'en/LinLibertine_RBah.ttf'
