site:
  domain: emoji.pine.moe
  description: 絵文字ジェネレーターで、綺麗な絵文字を生成しよう! 好みのテキストと色を指定するだけで、綺麗な絵文字が簡単に生成できます。

cache:
  version: 3 # integer

fonts:
  'notosans-mono-bold':
    name: 'Noto Sans Mono CJK Bold'
    file: 'NotoSansMonoCJKjp-Bold.otf'
    type: 'ゴシック'
    order: 1
  'mplus-1p-black':
    name: 'M+ 1p black'
    file: 'mplus-1p-black.ttf'
    type: '極太ゴシック'
    order: 2
  'migu-1m-bold':
    name: 'Migu 1m bold'
    file: 'migu-1m-bold.ttf'
    type: 'ゴシック'
    order: 3
  'rounded-x-mplus-1p-black':
    name: 'Rounded M+ 1p black'
    file: 'rounded-x-mplus-1p-black.ttf'
    type: '丸ゴシック'
    order: 4
  'aoyagireisyoshimo':
    name: '青柳隷書しも'
    file: 'aoyagireisyosimo_otf_2_01.otf'
    type: '毛筆'
    order: 5
